### ISSUE TITLE
Model Background

### ISSUE THREAD

**Issue by Nefeles82** [Miorey/wow-model-viewer#19]
Is there a way to make the background transparent? I tried to make the background transparent and there are models that look bad, mainly the models that have a flame effect.

**Comment by Miorey** [comment]
@Nefeles82 What do you mean by transparent background exactly ? Can you be more precise ?

**Comment by Nefeles82** [comment]
> @Nefeles82 What do you mean by transparent background exactly ? Can you be more precise ?

To the gray background where is the frame of the model.
