### ISSUE TITLE
Pages rendering blank.

### ISSUE THREAD

**Issue by UmbraChimera** [Miorey/wow-model-viewer#22]
Downloaded the most recent and .zip and when testing with the examples the pages are rendering blank.

Not sure if the api no longer works or I missed something obvious.

**Comment by Miorey** [comment]
It works I just check it:
<img width="290" alt="image" src="https://user-images.githubusercontent.com/10229998/211280941-83cf8cee-fc2f-4e94-9d46-f088792e3e28.png">
