### ISSUE TITLE
Hi Miorey, the CONTENT_PATH is not available now?

### ISSUE THREAD

**Issue by CarloLei** [Miorey/wow-model-viewer#23]
Thanks for your reply😊

**Comment by Miorey** [comment]
Hey @CarloLei sadly I have no alternative to this endpoint. It seems to work today ex: https://wow.zamimg.com/modelviewer/live/meta/armor/9/8413.json

**Comment by Miorey** [comment]
@CarloLei can I close this issue ?

**Comment by CarloLei** [comment]
@Miorey Sure, thank you
