### ISSUE TITLE
Updating model without regenerating it

### ISSUE THREAD

**Issue by Novivy** [Miorey/wow-model-viewer#29]
Would it be possible to change character traits (face, hair, skin..) on the model without regenerating it?

Wowhead let you do that: https://www.wowhead.com/classic/dressing-room#fz80z0zb89c8s8VV38a8Voo8q8Vow8b8Von8d8VoC877

**Comment by Miorey** [comment]
Not today but if Wowhead does it, it shall be possible. I will check that in a future version.

**Comment by Novivy** [comment]
any update on this? What can I do to help check that this is possible?

**Comment by Miorey** [comment]
@Novivy nope I didn't have time to work on it. I think I will deliver it in septembre. I have few time for this topic.

**Comment by Miorey** [comment]
@Novivy ET VOILA it's

**Comment by Novivy** [comment]
Thank you very much @Miorey
