### ISSUE TITLE
Download static files from zamimg

### ISSUE THREAD

**Issue by Friskes** [Miorey/wow-model-viewer#48]
Hi, is there a way to download an archive with static files somewhere that is requested from the site [zamimg](https://wow.zamimg.com) ?

**Comment by Miorey** [comment]
Hi @Friskes ,
Nope there is no way to do it, please take a look to https://github.com/Miorey/wow-model-viewer?tab=readme-ov-file#cors-policies section.

**Comment by Friskes** [comment]
It's sad because a month ago zamimg changed its api and I had to edit my code, I would like to be completely independent from the zamimg static server and have all the files locally,
https://frishub.ru/dressing-room/

**Comment by Helias** [comment]
I understand, but it's not empty, anyways, a good start would be use this https://github.com/Mugen87/three-m2loader or the wow.tools source code

**Comment by Miorey** [comment]
I close this issue as is not directly related to the lib.  
@Friskes  Good Luck in your quest !
