### ISSUE TITLE
Missing Concrete Examples of Usage

### ISSUE THREAD

**Issue by micaelparadox** [Miorey/wow-model-viewer#49]
Missing Examples, I'm trying to integrate it to my application using nodejs and express ex i would like a guide since i add your lib in my project, somehow I'm failing to load

@Miorey 

![image](https://github.com/Miorey/wow-model-viewer/assets/69440479/3acaf592-6601-4c4d-8e40-acc3a39da420)

![image](https://github.com/Miorey/wow-model-viewer/assets/69440479/18021f25-61e8-47c7-a140-cdb847f5c5b9)

**Comment by Miorey** [comment]
Hello @micaelparadox I try to make a video of the usage asap. Do you have a public branch of what you did ? Or can you invite me to your repo ?

**Comment by micaelparadox** [comment]
Sure
https://github.com/micaelparadox/chardev-wotlk

I will upload the branch regard the error Call it error-branch

**Comment by micaelparadox** [comment]
https://github.com/micaelparadox/chardev-wotlk/tree/error-branch

there is a branch and invited you tho

**Comment by micaelparadox** [comment]
![image](https://github.com/Miorey/wow-model-viewer/assets/69440479/b777774b-7ea5-418a-8f43-ffa88bafbac0)

now connection refused haha, i manage to skip the last erro with export class ZamModelViewer still im kind lost how to implement the view modeling my plan is to display based on my items in database, a certain of association with items, regard simalar to retail armory back in the days..  so when someone is creating a toon they have like a 3d model showing off.. in my app basicly in this dashboard i would like to display like a basic toon to test out..

**Comment by Miorey** [comment]
@micaelparadox I take a look on it tomorrow.

**Comment by Miorey** [comment]
Hey @micaelparadox I made a little upgrade of the lib to add a more simple usage of the demo so here are steps by steps what you have to do:
```sh
git clone https://github.com/Miorey/wow-model-viewer 
git switch demo
docker-compose up
http-server ./
```

If you haven’t  `docker-compose` for `docker compose` use this:
```
docker compose up
```

`npm install --global http-server` is required if not already done.

The demo works for me here: http://127.0.0.1:8080/demo.html

If the demo works to me the lib should work in your project. If it already don't I take a look to your project.

**Comment by micaelparadox** [comment]
Thanks, I'll check it out!
