### ISSUE TITLE
The Dracthyr is missing textures

### ISSUE THREAD

**Issue by 1486583368** [Miorey/wow-model-viewer#51]
![image](https://github.com/Miorey/wow-model-viewer/assets/57607736/91ad468f-7164-49cc-b15b-82e8eb9b1bbd)
The parameters are 
```
{
  race: 45,
  gender: 0
}
```
 It is normal in the wowhead dressing room 👇
![image](https://github.com/Miorey/wow-model-viewer/assets/57607736/85797c1b-000d-4b46-96ea-ddd1c587f35f)

**Comment by Miorey** [comment]
Thanks I will take a look

**Comment by Miorey** [comment]
Hmm interesting I will take a look
