### ISSUE TITLE
Add an alternative for SOD (classic) items

### ISSUE THREAD

**Issue by yrodrigez** [Miorey/wow-model-viewer#58]
There are some items that are failing when fetch.
IE: https://www.wowhead.com/classic/item=220588/cobra-fang-claw#dropped-by

This fails:
https://wow.zamimg.com/modelviewer/live/meta/item/679611.json

https://www.wowhead.com/classic/item=220750/fractured-mind-pauldrons
https://wow.zamimg.com/modelviewer/live/meta/armor/3/680018.json

@Miorey  do you have any alternative for this?

**Comment by Helias** [comment]
you could impleement a mechanism that checks if the call fails, if it fails it could rely on `classic` instead of `live`
[wow.zamimg.com/modelviewer/classic/meta/item/679611.json](https://wow.zamimg.com/modelviewer/classic/meta/item/679611.json)

**Comment by Miorey** [comment]
@Helias @yrodrigez I think I already implement something inside the lib I will check. A bit busy those times sorry for delay

**Comment by Miorey** [comment]
@yrodrigez I added a way to handle classis view.
I merged the new features to master and also a demo https://github.com/Miorey/wow-model-viewer/tree/demo
If you can take a look before i push the new npm version it will be cool.
