### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by query-wow** [Miorey/wow-model-viewer#6]
Hi, great lib, thank you a lot for sharing it!

Is is possible to disable the zoom function from the model viewer?

**Comment by Miorey** [comment]
Hi @query-wow , currently not but you can trick it by adding an empty `div` over your model. But in this case you will not be able to change the position. You have an example on my server https://wotlk.murlocvillage.com/fr/shop/ on the bottom of the page in the **Miroir, Ô mon beau miroir** section. 

In the next version I will add changing position / changing translation option.

**Comment by query-wow** [comment]
@Miorey  thanks for the reply! that's a smart idea actually. I don't think i mind losing that functionality :D i'll be on the look for more updates. Thanks for developing this!
