### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by Taliraz** [Miorey/wow-model-viewer#8]
Hi, 
I can't start the project i tried
npm start
ng serve
node index.js
but none of them works

**Comment by Miorey** [comment]
Hello @Taliraz this not a node server. You can do it with node using [http-server](https://stackoverflow.com/questions/38497334/how-to-run-html-file-on-localhost) I also add a vue js example. For vue you go in the folder:
```
npm i
npm run serve
```
If you have webstorm is the simplest way:
**Run demo** on the file you want:
![image](https://user-images.githubusercontent.com/10229998/161284122-af402fef-4814-4a0c-a9cc-0d6caf541e7a.png)

Good luck

**Comment by Taliraz** [comment]
Thanks ! 
Do you know how it is possible to adapt it to http-server?

**Comment by Taliraz** [comment]
Thank you
