### ISSUE TITLE
Remove jQuery/Axios dependencies

### ISSUE THREAD

**Issue by asfo** [Miorey/wow-model-viewer#9]
I see that jQuery is used for ajax requests and for a selector.

Maybe it could change that the selector states something like `document.getElementById()` and wrap everything with an alert that states the selector was not able to find that id.

And the Ajax requests are being done using the `fetch` JS API instead of Axios or jQuery.

So this project can work without any third-party dependencies or anything attached to it. In the end looks like it is a wrapper of the Zaml WoW Model Viewer which at least, make it easier to work with but there is no need to work with jQuery or Axios here.

Btw, I can work with that if you want.

**Comment by Miorey** [comment]
@asfo I didn't test this part, it remains when I extract the code from our server codebase. Any help is welcome.

**Comment by Miorey** [comment]
@asfo I add you to the project
